# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sistemaventaaplicacionweb:
    image: sistemaventaaplicacionweb
    build:
      context: .
      dockerfile: SistemaVenta.AplicacionWeb/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5222:5222
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - 1433:1433